version: '2'

services:
  jsonkeeper:
    build: ./JSONkeeper
    ports:
      - '8001:8000'
    volumes:
      - ./JSONkeeper/config.ini:/jsonkeeper/config.ini

  canvasindexer:
    build: ./Canvas-Indexer
    ports:
      - '8002:8000'
    volumes:
      - ./Canvas-Indexer/config.ini:/canvasindexer/config.ini
      - ./Canvas-Indexer/log.txt:/canvasindexer/log.txt

  curationviewer:
    build: ./IIIFCurationViewer
    ports:
      - '8081:80'

  curationfinder:
    build: ./IIIFCurationFinder
    ports:
      - '8082:80'
